language: php

php:
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/grumphp run
  - vendor/bin/phpunit tests --coverage-clover clover.xml

notifications:
  email:
    on_success: never
